---
# Dependency Review configuration
# Controls how the dependency review action behaves

# Fail if any vulnerabilities are found
fail-on-severity: moderate

# Allow specific licenses (matching deny.toml)
allow-licenses:
  - MIT
  - Apache-2.0
  - Apache-2.0 WITH LLVM-exception
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Unicode-DFS-2016
  - Unicode-3.0
  - CC0-1.0
  - 0BSD
  - Zlib
  - CDLA-Permissive-2.0

# Deny specific licenses
deny-licenses:
  - GPL-2.0
  - GPL-3.0
  - AGPL-1.0
  - AGPL-3.0
  - LGPL-2.0
  - LGPL-2.1
  - LGPL-3.0
  - CPAL-1.0
  - EPL-1.0
  - EPL-2.0
  - EUPL-1.1
  - EUPL-1.2

# Allow specific packages that might otherwise be flagged
allow-dependencies-licenses:
  - pkg:cargo/ring # Has complex licensing but is widely used and safe

# Fail if new dependencies are from external sources
fail-on-external-sources: true

# Check for security advisories
allow-ghsas: []

# Don't fail on these specific vulnerability IDs (use sparingly)
allow-vulnerabilities: []

# Comment configuration
comment-summary-in-pr: always
warn-only: false
