apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-management-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: media-management-service
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
