---
# k8s/configmap-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-management-config
  namespace: media-management
  labels:
    app: media-management-service
data:
  # Server Configuration
  MEDIA_SERVICE_SERVER_HOST: "0.0.0.0"
  MEDIA_SERVICE_SERVER_PORT: "3000"
  MEDIA_SERVICE_SERVER_MAX_UPLOAD_SIZE: "104857600"

  # Database Connection (non-sensitive)
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
  MEDIA_MANAGEMENT_DB_USER: "${MEDIA_MANAGEMENT_DB_USER}"
  DATABASE_MAX_CONNECTIONS: "10"
  DATABASE_MIN_CONNECTIONS: "1"
  DATABASE_ACQUIRE_TIMEOUT_SECONDS: "30"

  # Storage Configuration
  MEDIA_SERVICE_STORAGE_BASE_PATH: "/app/media"
  MEDIA_SERVICE_STORAGE_TEMP_PATH: "/app/media/temp"
  MEDIA_SERVICE_STORAGE_MAX_FILE_SIZE: "524288000"

  # Logging Configuration
  MEDIA_SERVICE_LOGGING_LEVEL: "info"
  MEDIA_SERVICE_LOGGING_FORMAT: "json"
