---
# k8s/configmap-template.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: media-management-config
  namespace: media-management
  labels:
    app: media-management-service
data:
  # Runtime Configuration
  RUN_MODE: "${RUN_MODE}"

  # Server Configuration
  MEDIA_SERVICE_SERVER_HOST: "${MEDIA_SERVICE_SERVER_HOST}"
  MEDIA_SERVICE_SERVER_PORT: "${MEDIA_SERVICE_SERVER_PORT}"
  MEDIA_SERVICE_SERVER_MAX_UPLOAD_SIZE: "${MEDIA_SERVICE_SERVER_MAX_UPLOAD_SIZE}"

  # Database Connection (non-sensitive)
  POSTGRES_HOST: "${POSTGRES_HOST}"
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_SCHEMA: "${POSTGRES_SCHEMA}"
  MEDIA_MANAGEMENT_DB_USER: "${MEDIA_MANAGEMENT_DB_USER}"
  POSTGRES_MAX_CONNECTIONS: "${POSTGRES_MAX_CONNECTIONS}"
  POSTGRES_MIN_CONNECTIONS: "${POSTGRES_MIN_CONNECTIONS}"
  POSTGRES_ACQUIRE_TIMEOUT_SECONDS: "${POSTGRES_ACQUIRE_TIMEOUT_SECONDS}"

  # Storage Configuration
  MEDIA_SERVICE_STORAGE_BASE_PATH: "${MEDIA_SERVICE_STORAGE_BASE_PATH}"
  MEDIA_SERVICE_STORAGE_TEMP_PATH: "${MEDIA_SERVICE_STORAGE_TEMP_PATH}"
  MEDIA_SERVICE_STORAGE_MAX_FILE_SIZE: "${MEDIA_SERVICE_STORAGE_MAX_FILE_SIZE}"

  # Logging Configuration
  MEDIA_SERVICE_LOGGING_LEVEL: "${MEDIA_SERVICE_LOGGING_LEVEL}"
  MEDIA_SERVICE_LOGGING_CONSOLE_ENABLED: "${MEDIA_SERVICE_LOGGING_CONSOLE_ENABLED}"
  MEDIA_SERVICE_LOGGING_CONSOLE_FORMAT: "${MEDIA_SERVICE_LOGGING_CONSOLE_FORMAT}"
  MEDIA_SERVICE_LOGGING_FILE_ENABLED: "${MEDIA_SERVICE_LOGGING_FILE_ENABLED}"
  MEDIA_SERVICE_LOGGING_FILE_FORMAT: "${MEDIA_SERVICE_LOGGING_FILE_FORMAT}"
  MEDIA_SERVICE_LOGGING_FILE_PATH: "${MEDIA_SERVICE_LOGGING_FILE_PATH}"
  MEDIA_SERVICE_LOGGING_FILE_PREFIX: "${MEDIA_SERVICE_LOGGING_FILE_PREFIX}"
  MEDIA_SERVICE_LOGGING_FILE_ROTATION: "${MEDIA_SERVICE_LOGGING_FILE_ROTATION}"
  MEDIA_SERVICE_LOGGING_FILE_RETENTION_DAYS: "${MEDIA_SERVICE_LOGGING_FILE_RETENTION_DAYS}"
  MEDIA_SERVICE_LOGGING_NON_BLOCKING: "${MEDIA_SERVICE_LOGGING_NON_BLOCKING}"
  MEDIA_SERVICE_LOGGING_BUFFER_SIZE: "${MEDIA_SERVICE_LOGGING_BUFFER_SIZE}"

  # Authentication Configuration
  MEDIA_SERVICE_MIDDLEWARE_AUTH_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_AUTH_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_AUTH_JWT_SECRET: "${MEDIA_SERVICE_MIDDLEWARE_AUTH_JWT_SECRET}"
  MEDIA_SERVICE_MIDDLEWARE_AUTH_JWT_EXPIRY_HOURS: "${MEDIA_SERVICE_MIDDLEWARE_AUTH_JWT_EXPIRY_HOURS}"
  MEDIA_SERVICE_MIDDLEWARE_AUTH_REQUIRE_AUTH_ROUTES: "${MEDIA_SERVICE_MIDDLEWARE_AUTH_REQUIRE_AUTH_ROUTES}"
  MEDIA_SERVICE_MIDDLEWARE_AUTH_OPTIONAL_AUTH_ROUTES: "${MEDIA_SERVICE_MIDDLEWARE_AUTH_OPTIONAL_AUTH_ROUTES}"

  # OAuth2 Service Configuration
  OAUTH2_SERVICE_ENABLED: "${OAUTH2_SERVICE_ENABLED}"
  OAUTH2_SERVICE_TO_SERVICE_ENABLED: "${OAUTH2_SERVICE_TO_SERVICE_ENABLED}"
  OAUTH2_INTROSPECTION_ENABLED: "${OAUTH2_INTROSPECTION_ENABLED}"
  OAUTH2_CLIENT_ID: "${OAUTH2_CLIENT_ID}"
  OAUTH2_SERVICE_BASE_URL: "${OAUTH2_SERVICE_BASE_URL}"
  OAUTH2_TOKEN_CACHE_TTL_SECONDS: "${OAUTH2_TOKEN_CACHE_TTL_SECONDS}"
  OAUTH2_CLIENT_CREDENTIALS_CACHE_TTL_SECONDS: "${OAUTH2_CLIENT_CREDENTIALS_CACHE_TTL_SECONDS}"
  OAUTH2_REQUEST_TIMEOUT_SECONDS: "${OAUTH2_REQUEST_TIMEOUT_SECONDS}"
  OAUTH2_MAX_RETRIES: "${OAUTH2_MAX_RETRIES}"
  OAUTH2_RETRY_DELAY_MS: "${OAUTH2_RETRY_DELAY_MS}"

  # JWT Configuration (must match auth service)
  JWT_SECRET: "${JWT_SECRET}"

  # Rate Limiting Configuration
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_DEFAULT_REQUESTS_PER_MINUTE: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_DEFAULT_REQUESTS_PER_MINUTE}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_DEFAULT_BURST_CAPACITY: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_DEFAULT_BURST_CAPACITY}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TRUST_FORWARDED_HEADERS: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TRUST_FORWARDED_HEADERS}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_INCLUDE_RATE_LIMIT_HEADERS: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_INCLUDE_RATE_LIMIT_HEADERS}"

  # Rate Limiting Tiers
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_HEALTH_REQUESTS_PER_MINUTE: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_HEALTH_REQUESTS_PER_MINUTE}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_PUBLIC_REQUESTS_PER_MINUTE: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_PUBLIC_REQUESTS_PER_MINUTE}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_AUTHENTICATED_REQUESTS_PER_MINUTE:
    >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_AUTHENTICATED_REQUESTS_PER_MINUTE}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_UPLOAD_REQUESTS_PER_MINUTE: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_UPLOAD_REQUESTS_PER_MINUTE}"
  MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_ADMIN_REQUESTS_PER_MINUTE: >
    "${MEDIA_SERVICE_MIDDLEWARE_RATE_LIMITING_TIERS_ADMIN_REQUESTS_PER_MINUTE}"

  # Security Headers Configuration
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_MAX_AGE_SECONDS: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_MAX_AGE_SECONDS}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_INCLUDE_SUBDOMAINS: >
    "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_INCLUDE_SUBDOMAINS}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_PRELOAD: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_HSTS_PRELOAD}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_CSP_POLICY: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_CSP_POLICY}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_FRAME_OPTIONS: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_FRAME_OPTIONS}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_CONTENT_TYPE_OPTIONS: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_CONTENT_TYPE_OPTIONS}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_XSS_PROTECTION: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_XSS_PROTECTION}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_REFERRER_POLICY: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_REFERRER_POLICY}"
  MEDIA_SERVICE_MIDDLEWARE_SECURITY_PERMISSIONS_POLICY: "${MEDIA_SERVICE_MIDDLEWARE_SECURITY_PERMISSIONS_POLICY}"

  # Metrics Collection Configuration
  MEDIA_SERVICE_MIDDLEWARE_METRICS_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_ENDPOINT_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_ENDPOINT_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_ENDPOINT_PATH: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_ENDPOINT_PATH}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_PROMETHEUS_PORT: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_PROMETHEUS_PORT}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_REQUEST_METRICS: >
    "${MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_REQUEST_METRICS}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_TIMING_METRICS: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_TIMING_METRICS}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_ERROR_METRICS: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_ERROR_METRICS}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_BUSINESS_METRICS: >
    "${MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECT_BUSINESS_METRICS}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_NORMALIZE_ROUTES: "${MEDIA_SERVICE_MIDDLEWARE_METRICS_NORMALIZE_ROUTES}"
  MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECTION_INTERVAL_SECONDS: >
    "${MEDIA_SERVICE_MIDDLEWARE_METRICS_COLLECTION_INTERVAL_SECONDS}"

  # Request Validation Configuration
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_CONTENT_TYPE: >
    "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_CONTENT_TYPE}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_BODY_SIZE: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_BODY_SIZE}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_MAX_BODY_SIZE_MB: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_MAX_BODY_SIZE_MB}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_JSON_STRUCTURE: >
    "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_JSON_STRUCTURE}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_FILE_UPLOADS: >
    "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_FILE_UPLOADS}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_MAX_FILE_SIZE_MB: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_MAX_FILE_SIZE_MB}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_ALLOWED_FILE_TYPES: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_ALLOWED_FILE_TYPES}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_HEADERS: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_HEADERS}"
  MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_METHODS: "${MEDIA_SERVICE_MIDDLEWARE_VALIDATION_VALIDATE_METHODS}"

  # Request/Response Logging Configuration
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_ENABLED: "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_ENABLED}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_REQUEST_BODY: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_REQUEST_BODY}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_RESPONSE_BODY: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_RESPONSE_BODY}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_MAX_BODY_SIZE_KB: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_MAX_BODY_SIZE_KB}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_REQUEST_HEADERS: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_REQUEST_HEADERS}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_RESPONSE_HEADERS: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_RESPONSE_HEADERS}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_EXCLUDED_HEADERS: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_EXCLUDED_HEADERS}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_TIMING: "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_LOG_TIMING}"
  MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_SLOW_REQUEST_THRESHOLD_MS: >
    "${MEDIA_SERVICE_MIDDLEWARE_REQUEST_LOGGING_SLOW_REQUEST_THRESHOLD_MS}"
