---
# k8s/poddisruptionbudget.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: media-management-pdb
  namespace: media-management
  labels:
    app: media-management-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: media-management-service
