---
# k8s/secret-template.yaml
apiVersion: v1
kind: Secret
metadata:
  name: media-management-secrets
  namespace: media-management
  labels:
    app: media-management-service
type: Opaque
stringData:
  # Database password (only sensitive item)
  MEDIA_MANAGEMENT_DB_PASSWORD: "${MEDIA_MANAGEMENT_DB_PASSWORD}"
