---
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/jsamuelsen/recipe-web-app/wiki
    about: Check the documentation for usage guides and API reference
  - name: 💬 Discussion
    url: https://github.com/jsamuelsen/recipe-web-app/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/jsamuelsen/recipe-web-app/security/advisories/new
    about: Report security vulnerabilities privately
