---
name: Feature Request
description: Suggest a new feature or enhancement for the media management service
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us
        understand and evaluate your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: dropdown
    id: component
    attributes:
      label: Component Area
      description: Which area does this feature relate to?
      options:
        - File Upload/Download
        - Media Processing
        - Image Formats
        - Video Processing
        - Storage Management
        - API Endpoints
        - Database/Persistence
        - Authentication/Authorization
        - Performance/Optimization
        - Configuration
        - Documentation
        - Kubernetes Deployment
        - Monitoring/Metrics
        - CLI Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my use case)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        How would you use this feature?
        Who would benefit from it?
        What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If this affects the API, describe the desired interface
      placeholder: |
        Request format:
        POST /api/v1/media-management/new-endpoint
        {
          "field": "value"
        }

        Response format:
        {
          "result": "..."
        }

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature introduce breaking changes?
      options:
        - label: This feature may introduce breaking changes
          required: false

  - type: checkboxes
    id: security
    attributes:
      label: Security Implications
      description: Does this feature have security implications?
      options:
        - label: This feature has security implications that need review
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: Links to similar features, mockups, code examples, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I am willing to help implement this feature
          required: false
