---
name: Security Vulnerability (Public)
description: Report a low-severity security issue (use GitHub Security Advisories for critical issues)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - jsamuelsen11
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For critical security vulnerabilities, please use
        [GitHub Security Advisories](https://github.com/Recipe-Web-App/media-management-service/security/advisories/new)
        instead of this public form.

        Use this form only for:
        - Low-severity security concerns
        - Security improvements
        - Best practice suggestions
        - Dependency vulnerabilities (also reported by Dependabot)

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (Informational/Best Practice)
        - Medium (Requires specific conditions to exploit)
        - High (Should use GitHub Security Advisories instead)
        - Critical (Should use GitHub Security Advisories instead)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security concern or vulnerability
      placeholder: Please provide a clear description of the security issue
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - File Upload Validation
        - Path Traversal
        - Authentication/Authorization
        - Input Validation
        - Cryptography
        - Dependency Vulnerability
        - Information Disclosure
        - Rate Limiting/DoS
        - CORS/Security Headers
        - Secret Management
        - Database Security
        - Storage Security
        - Malware Detection
        - File Content Validation
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve?
      placeholder: Describe the potential security impact
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: How can this issue be reproduced? (if safe to share publicly)
      placeholder: |
        1. Configure service with...
        2. Upload file with...
        3. Observe security issue...

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected?
      options:
        - File Upload System
        - File Download System
        - Storage Layer
        - API Endpoints
        - Authentication Layer
        - Database Layer
        - Media Processing
        - Configuration
        - Dependencies
        - Docker Container
        - Kubernetes Deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      value: |
        - Service Version:
        - Deployment: (Docker/Kubernetes/Local)
        - Configuration:

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this issue
      placeholder: Describe potential fixes or mitigations

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Confirmation of responsible disclosure
      options:
        - label: I understand this is a public issue and am not disclosing critical vulnerabilities here
          required: true
        - label: I have checked that this is not already reported in Security Advisories
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details, references, or context
