apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app: media-management-service
      part-of: recipe-web-app

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
